"""Added language guess to post

Revision ID: 662f699c0f85
Revises: 59b331a01e7c
Create Date: 2022-09-20 16:32:05.178093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662f699c0f85'
down_revision = '59b331a01e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
